var namespaceLeosac =
[
    [ "Audit", "d9/db5/namespaceLeosac_1_1Audit.html", "d9/db5/namespaceLeosac_1_1Audit" ],
    [ "Auth", "d0/d31/namespaceLeosac_1_1Auth.html", "d0/d31/namespaceLeosac_1_1Auth" ],
    [ "Colorize", "db/d31/namespaceLeosac_1_1Colorize.html", null ],
    [ "Cred", "d6/d02/namespaceLeosac_1_1Cred.html", "d6/d02/namespaceLeosac_1_1Cred" ],
    [ "db", "dc/d75/namespaceLeosac_1_1db.html", "dc/d75/namespaceLeosac_1_1db" ],
    [ "Ex", "d6/d8b/namespaceLeosac_1_1Ex.html", "d6/d8b/namespaceLeosac_1_1Ex" ],
    [ "Hardware", "df/d19/namespaceLeosac_1_1Hardware.html", "df/d19/namespaceLeosac_1_1Hardware" ],
    [ "Module", "df/dc3/namespaceLeosac_1_1Module.html", "df/dc3/namespaceLeosac_1_1Module" ],
    [ "service_event", "d5/d81/namespaceLeosac_1_1service__event.html", "d5/d81/namespaceLeosac_1_1service__event" ],
    [ "Tasks", "d9/d80/namespaceLeosac_1_1Tasks.html", "d9/d80/namespaceLeosac_1_1Tasks" ],
    [ "Test", "d5/d42/namespaceLeosac_1_1Test.html", "d5/d42/namespaceLeosac_1_1Test" ],
    [ "Tools", "d4/da4/namespaceLeosac_1_1Tools.html", "d4/da4/namespaceLeosac_1_1Tools" ],
    [ "update", "d3/db1/namespaceLeosac_1_1update.html", "d3/db1/namespaceLeosac_1_1update" ],
    [ "AccessPointJSONSerializer", "df/d27/structLeosac_1_1AccessPointJSONSerializer.html", null ],
    [ "AccessPointJSONStringSerializer", "d9/d85/structLeosac_1_1AccessPointJSONStringSerializer.html", null ],
    [ "AtMostOneCombiner", "dc/dee/structLeosac_1_1AtMostOneCombiner.html", "dc/dee/structLeosac_1_1AtMostOneCombiner" ],
    [ "ConfigChecker", "d4/d3f/classLeosac_1_1ConfigChecker.html", "d4/d3f/classLeosac_1_1ConfigChecker" ],
    [ "ConfigManager", "d4/d7a/classLeosac_1_1ConfigManager.html", "d4/d7a/classLeosac_1_1ConfigManager" ],
    [ "CoreAPI", "db/d7c/classLeosac_1_1CoreAPI.html", "db/d7c/classLeosac_1_1CoreAPI" ],
    [ "CoreUtils", "d9/d46/classLeosac_1_1CoreUtils.html", "d9/d46/classLeosac_1_1CoreUtils" ],
    [ "CredentialJSONSerializer", "d7/d5f/structLeosac_1_1CredentialJSONSerializer.html", null ],
    [ "CredentialJSONStringSerializer", "dc/d5d/structLeosac_1_1CredentialJSONStringSerializer.html", null ],
    [ "DBService", "d7/def/classLeosac_1_1DBService.html", "d7/def/classLeosac_1_1DBService" ],
    [ "DoorJSONSerializer", "d9/d14/structLeosac_1_1DoorJSONSerializer.html", null ],
    [ "DoorJSONStringSerializer", "db/d29/structLeosac_1_1DoorJSONStringSerializer.html", null ],
    [ "EntityNotFound", "d8/d1b/classLeosac_1_1EntityNotFound.html", "d8/d1b/classLeosac_1_1EntityNotFound" ],
    [ "ExecutionContext", "d5/dba/structLeosac_1_1ExecutionContext.html", "d5/dba/structLeosac_1_1ExecutionContext" ],
    [ "ExtensibleSerializer", "d4/d6b/classLeosac_1_1ExtensibleSerializer.html", "d4/d6b/classLeosac_1_1ExtensibleSerializer" ],
    [ "GlobalRegistry", "dc/df7/classLeosac_1_1GlobalRegistry.html", "dc/df7/classLeosac_1_1GlobalRegistry" ],
    [ "GroupJSONSerializer", "d8/dca/structLeosac_1_1GroupJSONSerializer.html", null ],
    [ "GroupJSONStringSerializer", "d4/d19/structLeosac_1_1GroupJSONStringSerializer.html", null ],
    [ "InvalidArgument", "d6/daa/classLeosac_1_1InvalidArgument.html", "d6/daa/classLeosac_1_1InvalidArgument" ],
    [ "is_shared_ptr", "df/d84/structLeosac_1_1is__shared__ptr.html", null ],
    [ "is_shared_ptr< const std::shared_ptr< T > & >", "de/d56/structLeosac_1_1is__shared__ptr_3_01const_01std_1_1shared__ptr_3_01T_01_4_01_6_01_4.html", null ],
    [ "is_shared_ptr< const std::shared_ptr< T > >", "d8/d1b/structLeosac_1_1is__shared__ptr_3_01const_01std_1_1shared__ptr_3_01T_01_4_01_4.html", null ],
    [ "is_shared_ptr< std::shared_ptr< T > & >", "d5/df2/structLeosac_1_1is__shared__ptr_3_01std_1_1shared__ptr_3_01T_01_4_01_6_01_4.html", null ],
    [ "is_shared_ptr< std::shared_ptr< T > >", "d8/df9/structLeosac_1_1is__shared__ptr_3_01std_1_1shared__ptr_3_01T_01_4_01_4.html", null ],
    [ "JSONSerializer", "d3/d6a/structLeosac_1_1JSONSerializer.html", null ],
    [ "Kernel", "d1/d50/classLeosac_1_1Kernel.html", "d1/d50/classLeosac_1_1Kernel" ],
    [ "MailInfo", "db/dd0/structLeosac_1_1MailInfo.html", "db/dd0/structLeosac_1_1MailInfo" ],
    [ "NetworkConfig", "d2/d91/classLeosac_1_1NetworkConfig.html", "d2/d91/classLeosac_1_1NetworkConfig" ],
    [ "NullSecurityContext", "d2/d3e/classLeosac_1_1NullSecurityContext.html", "d2/d3e/classLeosac_1_1NullSecurityContext" ],
    [ "PinCodeJSONSerializer", "d7/d04/structLeosac_1_1PinCodeJSONSerializer.html", null ],
    [ "PolymorphicCredentialJSONSerializer", "d7/dfb/structLeosac_1_1PolymorphicCredentialJSONSerializer.html", "d7/dfb/structLeosac_1_1PolymorphicCredentialJSONSerializer" ],
    [ "PolymorphicCredentialJSONStringSerializer", "dc/d08/structLeosac_1_1PolymorphicCredentialJSONStringSerializer.html", null ],
    [ "Registry", "d0/da7/classLeosac_1_1Registry.html", "d0/da7/classLeosac_1_1Registry" ],
    [ "RegistryKeyNotFoundException", "d9/d76/classLeosac_1_1RegistryKeyNotFoundException.html", "d9/d76/classLeosac_1_1RegistryKeyNotFoundException" ],
    [ "RemoteConfigCollector", "d2/d93/classLeosac_1_1RemoteConfigCollector.html", "d2/d93/classLeosac_1_1RemoteConfigCollector" ],
    [ "RemoteControl", "d7/d42/classLeosac_1_1RemoteControl.html", "d7/d42/classLeosac_1_1RemoteControl" ],
    [ "RemoteControlSecurity", "d5/df3/classLeosac_1_1RemoteControlSecurity.html", "d5/df3/classLeosac_1_1RemoteControlSecurity" ],
    [ "RFIDCardJSONSerializer", "dc/d6f/structLeosac_1_1RFIDCardJSONSerializer.html", null ],
    [ "Scheduler", "d4/dde/classLeosac_1_1Scheduler.html", "d4/dde/classLeosac_1_1Scheduler" ],
    [ "SecurityContext", "db/d24/classLeosac_1_1SecurityContext.html", "db/d24/classLeosac_1_1SecurityContext" ],
    [ "ServiceRegistry", "df/d75/classLeosac_1_1ServiceRegistry.html", "df/d75/classLeosac_1_1ServiceRegistry" ],
    [ "SMTPService", "df/d5f/classLeosac_1_1SMTPService.html", "df/d5f/classLeosac_1_1SMTPService" ],
    [ "SystemExecutionContext", "d4/d4b/structLeosac_1_1SystemExecutionContext.html", "d4/d4b/structLeosac_1_1SystemExecutionContext" ],
    [ "SystemSecurityContext", "dd/dc0/classLeosac_1_1SystemSecurityContext.html", "dd/dc0/classLeosac_1_1SystemSecurityContext" ],
    [ "TestAccess", "dd/d78/structLeosac_1_1TestAccess.html", null ],
    [ "ThreadLocalRegistry", "d9/dd1/classLeosac_1_1ThreadLocalRegistry.html", "d9/dd1/classLeosac_1_1ThreadLocalRegistry" ],
    [ "UserGroupMembershipJSONSerializer", "de/d67/structLeosac_1_1UserGroupMembershipJSONSerializer.html", null ],
    [ "UserGroupMembershipJSONStringSerializer", "d3/d80/structLeosac_1_1UserGroupMembershipJSONStringSerializer.html", null ],
    [ "UserJSONSerializer", "d9/d17/structLeosac_1_1UserJSONSerializer.html", null ],
    [ "UserJSONStringSerializer", "df/d3b/structLeosac_1_1UserJSONStringSerializer.html", null ],
    [ "UserSecurityContext", "da/d85/classLeosac_1_1UserSecurityContext.html", "da/d85/classLeosac_1_1UserSecurityContext" ],
    [ "UUID", "d7/d46/classLeosac_1_1UUID.html", "d7/d46/classLeosac_1_1UUID" ],
    [ "VectorAppenderCombiner", "db/da9/structLeosac_1_1VectorAppenderCombiner.html", "db/da9/structLeosac_1_1VectorAppenderCombiner" ],
    [ "ZoneJSONSerializer", "de/d24/structLeosac_1_1ZoneJSONSerializer.html", null ],
    [ "ZoneJSONStringSerializer", "d2/d1a/structLeosac_1_1ZoneJSONStringSerializer.html", null ]
];